### ISSUE TITLE
add post render label in chart resources

### ISSUE THREAD

**Issue by matteogastaldello** [krateoplatformops/composition-dynamic-controller#52]
**Is your feature request related to a problem? Please describe.**
```yaml
krateo.io/composition-apiVersion: composition.krateo.io/v1-1-3

krateo.io/composition-name: demolive

krateo.io/composition-namespace: fireworksapp-system

krateo.io/composition-resource: fireworksapps
```
